[W-12591692] Adding missing dependency to avoid some warnings (#685)
* [W-12591692] Adding missing dependency to avoid some warnings
* [W-12593543] Updating dependency to avoid a NoSuchMethodError exception